import {
  AgentType,
  IAgentConfig,
  AgentCategory,
  ConnectionProfile,
  ReasoningProfile,
  LLMProvider,
  MiniMaxModel,
  SafetyTier,
  EvolutionMode,
} from './types/index';
import { TOOLS, UNIVERSAL_SYSTEM_TOOLS } from './constants/tools';
import {
  SUPERCLAW_SYSTEM_PROMPT,
  CODER_SYSTEM_PROMPT,
  PLANNER_SYSTEM_PROMPT,
  REFLECTOR_SYSTEM_PROMPT,
  QA_SYSTEM_PROMPT,
  CRITIC_SYSTEM_PROMPT,
  FACILITATOR_SYSTEM_PROMPT,
  MERGER_SYSTEM_PROMPT,
  RESEARCHER_SYSTEM_PROMPT,
  JUDGE_SYSTEM_PROMPT,
} from '../agents/prompts/index';

/**
 * Backbone Registry: The single source of truth for essential system components.
 * Reserved for LLM-based Agents and logic-based Handlers.
 */

const DEFAULT_LLM = {
  provider: LLMProvider.MINIMAX,
  model: MiniMaxModel.M2_7,
};

const BASE_CONFIG = {
  isBackbone: true,
  parallelToolCalls: false,
  evolutionMode: EvolutionMode.HITL,
  maxIterations: 10,
  safetyTier: SafetyTier.PROD,
  connectionProfile: [
    ConnectionProfile.BUS,
    ConnectionProfile.MEMORY,
    ConnectionProfile.CONFIG,
    ConnectionProfile.TRACE,
    ConnectionProfile.KNOWLEDGE,
  ],
  trustScore: 80,
  ...DEFAULT_LLM,
};

export const BACKBONE_REGISTRY: Record<string, IAgentConfig> = {
  [AgentType.SUPERCLAW]: {
    ...BASE_CONFIG,
    id: AgentType.SUPERCLAW,
    name: 'SuperClaw',
    systemPrompt: SUPERCLAW_SYSTEM_PROMPT,
    description: 'Orchestrator node. Directs traffic, retrieves memory, and delegates tasks.',
    category: AgentCategory.SYSTEM,
    icon: 'Bot',
    enabled: true,
    reasoningProfile: ReasoningProfile.STANDARD,
    defaultCommunicationMode: 'text',
    evolutionMode: EvolutionMode.AUTO,
    tools: [
      ...UNIVERSAL_SYSTEM_TOOLS,
      TOOLS.dispatchTask,
      TOOLS.signalOrchestration,
      TOOLS.listAgents,
      TOOLS.renderComponent,
      TOOLS.navigateTo,
      TOOLS.uiAction,
    ],
  },
  [AgentType.CODER]: {
    ...BASE_CONFIG,
    id: AgentType.CODER,
    name: 'Coder Agent',
    systemPrompt: CODER_SYSTEM_PROMPT,
    description: 'Autonomous builder. Implements changes and validates via pre-flight checks.',
    category: AgentCategory.SYSTEM,
    icon: 'Code',
    enabled: true,
    reasoningProfile: ReasoningProfile.DEEP,
    defaultCommunicationMode: 'json',
    safetyTier: SafetyTier.LOCAL,
    tools: [
      ...UNIVERSAL_SYSTEM_TOOLS,
      TOOLS.runTests,
      TOOLS.runShellCommand,
      TOOLS.stageChanges,
      TOOLS.generatePatch,
      TOOLS.triggerDeployment,
      TOOLS.validateCode,
      TOOLS.checkHealth,
      TOOLS.inspectTrace,
      TOOLS.inspectTopology,
      TOOLS.requestResearch,
      'aws-s3_read_file',
      'aws-s3_write_file',
      'aws-s3_list_objects',
      'filesystem_read_file',
      'filesystem_write_file',
      'filesystem_list_directory',
      'filesystem_search_files',
      'git_status',
      'git_diff',
      'grep_search',
      'google-search_search',
      'puppeteer_navigate',
      'puppeteer_screenshot',
      'puppeteer_click',
      'fetch_get',
      'aws_list_resources',
      'aws_get_resource',
      TOOLS.renderComponent,
      TOOLS.uiAction,
    ],
    maxIterations: 50,
    connectionProfile: [
      ...BASE_CONFIG.connectionProfile,
      ConnectionProfile.STORAGE,
      ConnectionProfile.CODEBUILD,
    ],
  },
  [AgentType.STRATEGIC_PLANNER]: {
    ...BASE_CONFIG,
    id: AgentType.STRATEGIC_PLANNER,
    name: 'Strategic Planner',
    systemPrompt: PLANNER_SYSTEM_PROMPT,
    description: 'Design node. Identifies missing features and architecting upgrades.',
    category: AgentCategory.SYSTEM,
    icon: 'Brain',
    enabled: true,
    reasoningProfile: ReasoningProfile.DEEP,
    defaultCommunicationMode: 'json',
    tools: [
      ...UNIVERSAL_SYSTEM_TOOLS,
      TOOLS.signalOrchestration,
      TOOLS.technicalResearch,
      TOOLS.dispatchTask,
      TOOLS.manageGap,
      TOOLS.reportGap,
      TOOLS.requestResearch,
      TOOLS.listAgents,
      TOOLS.createAgent,
      TOOLS.deleteAgent,
      TOOLS.syncAgentRegistry,
      TOOLS.manageAgentTools,
      TOOLS.inspectTopology,
      TOOLS.checkConfig,
      TOOLS.registerMCPServer,
      TOOLS.triggerInfraRebuild,
      TOOLS.triggerBatchEvolution,
      TOOLS.createCollaboration,
      TOOLS.joinCollaboration,
      TOOLS.getCollaborationContext,
      TOOLS.writeToCollaboration,
      TOOLS.closeCollaboration,
      TOOLS.listMyCollaborations,
      TOOLS.renderComponent,
      TOOLS.uiAction,
    ],
  },
  [AgentType.COGNITION_REFLECTOR]: {
    ...BASE_CONFIG,
    id: AgentType.COGNITION_REFLECTOR,
    name: 'Cognition Reflector',
    systemPrompt: REFLECTOR_SYSTEM_PROMPT,
    description: 'Intelligence audit node. Extracts facts, lessons, and gaps from logs.',
    category: AgentCategory.SYSTEM,
    icon: 'Search',
    enabled: true,
    reasoningProfile: ReasoningProfile.STANDARD,
    defaultCommunicationMode: 'json',
    tools: [
      ...UNIVERSAL_SYSTEM_TOOLS,
      TOOLS.manageGap,
      TOOLS.reportGap,
      TOOLS.prioritizeMemory,
      TOOLS.deleteTraces,
      TOOLS.inspectTrace,
      TOOLS.scanMetabolism,
    ],
  },
  [AgentType.QA]: {
    ...BASE_CONFIG,
    id: AgentType.QA,
    name: 'QA Auditor',
    systemPrompt: QA_SYSTEM_PROMPT,
    description: 'Validation node. Audits deployments to ensure they actually solve the gaps.',
    category: AgentCategory.SYSTEM,
    icon: 'FlaskConical',
    enabled: true,
    reasoningProfile: ReasoningProfile.STANDARD,
    defaultCommunicationMode: 'json',
    tools: [...UNIVERSAL_SYSTEM_TOOLS, TOOLS.checkHealth, TOOLS.triggerTrunkSync],
  },
  [AgentType.CRITIC]: {
    ...BASE_CONFIG,
    id: AgentType.CRITIC,
    name: 'Critic Agent',
    systemPrompt: CRITIC_SYSTEM_PROMPT,
    description:
      'Peer review node. Performs security, performance, and architectural reviews for the Council of Agents.',
    category: AgentCategory.SYSTEM,
    icon: 'Shield',
    enabled: true,
    reasoningProfile: ReasoningProfile.THINKING,
    defaultCommunicationMode: 'json',
    tools: [
      ...UNIVERSAL_SYSTEM_TOOLS,
      TOOLS.createCollaboration,
      TOOLS.joinCollaboration,
      TOOLS.getCollaborationContext,
      TOOLS.writeToCollaboration,
      TOOLS.closeCollaboration,
      TOOLS.listMyCollaborations,
      'filesystem_read_file',
      'filesystem_list_directory',
      'grep_search',
    ],
  },
  [AgentType.FACILITATOR]: {
    ...BASE_CONFIG,
    id: AgentType.FACILITATOR,
    name: 'Facilitator',
    systemPrompt: FACILITATOR_SYSTEM_PROMPT,
    description: 'Moderator node. Manages multi-party collaboration sessions and drives consensus.',
    category: AgentCategory.SYSTEM,
    icon: 'MessageSquareShare',
    enabled: true,
    reasoningProfile: ReasoningProfile.STANDARD,
    defaultCommunicationMode: 'text',
    tools: [
      ...UNIVERSAL_SYSTEM_TOOLS,
      TOOLS.createCollaboration,
      TOOLS.joinCollaboration,
      TOOLS.getCollaborationContext,
      TOOLS.writeToCollaboration,
      TOOLS.closeCollaboration,
      TOOLS.listMyCollaborations,
      TOOLS.broadcastMessage,
    ],
  },
  [AgentType.MERGER]: {
    ...BASE_CONFIG,
    id: AgentType.MERGER,
    name: 'Structural Merger',
    systemPrompt: MERGER_SYSTEM_PROMPT,
    description: 'Reconciliation node. Resolves semantic conflicts between parallel code changes.',
    category: AgentCategory.SYSTEM,
    icon: 'GitMerge',
    enabled: true,
    reasoningProfile: ReasoningProfile.THINKING,
    defaultCommunicationMode: 'json',
    tools: [
      ...UNIVERSAL_SYSTEM_TOOLS,
      TOOLS.technicalResearch,
      TOOLS.requestResearch,
      'filesystem_read_file',
      'filesystem_list_directory',
      'git_status',
      'git_diff',
      'grep_search',
      'ast_search_code',
      'ast_get_file_structure',
    ],
    connectionProfile: [...BASE_CONFIG.connectionProfile, ConnectionProfile.STORAGE],
  },
  [AgentType.BUILD_MONITOR]: {
    ...BASE_CONFIG,
    id: AgentType.BUILD_MONITOR,
    name: 'Build Monitor',
    systemPrompt: 'LOGIC_ONLY',
    description: 'Observability node. Watches builds, updates gaps, and discovers infra.',
    category: AgentCategory.SYSTEM,
    icon: 'Activity',
    enabled: true,
    reasoningProfile: ReasoningProfile.FAST,
    tools: [],
    connectionProfile: [
      ConnectionProfile.BUS,
      ConnectionProfile.CONFIG,
      ConnectionProfile.CODEBUILD,
      ConnectionProfile.MEMORY,
    ],
  },
  [AgentType.RECOVERY]: {
    ...BASE_CONFIG,
    id: AgentType.RECOVERY,
    name: "Dead Man's Switch",
    systemPrompt: 'LOGIC_ONLY',
    description: 'Resilience node. Performs health probes and emergency git-reverts.',
    category: AgentCategory.SYSTEM,
    icon: 'ShieldCheck',
    enabled: true,
    reasoningProfile: ReasoningProfile.FAST,
    tools: [],
    connectionProfile: [ConnectionProfile.DEPLOYER, ConnectionProfile.MEMORY_TABLE],
  },
  [AgentType.RESEARCHER]: {
    ...BASE_CONFIG,
    id: AgentType.RESEARCHER,
    name: 'Researcher',
    systemPrompt: RESEARCHER_SYSTEM_PROMPT,
    description: 'Technical discovery node. Researches libraries, frameworks, and patterns.',
    category: AgentCategory.SYSTEM,
    icon: 'Microscope',
    enabled: true,
    reasoningProfile: ReasoningProfile.THINKING,
    defaultCommunicationMode: 'text',
    tools: [
      ...UNIVERSAL_SYSTEM_TOOLS,
      TOOLS.reportGap,
      'google-search_search',
      'fetch_get',
      'puppeteer_navigate',
      'puppeteer_screenshot',
      'puppeteer_click',
    ],
  },
  [AgentType.EVENT_HANDLER]: {
    ...BASE_CONFIG,
    id: AgentType.EVENT_HANDLER,
    name: 'Event Handler',
    systemPrompt: 'LOGIC_ONLY',
    description: 'Event processing handler. Routes and processes EventBridge events.',
    category: AgentCategory.SYSTEM,
    icon: 'Event',
    enabled: true,
    reasoningProfile: ReasoningProfile.STANDARD,
    maxIterations: 1,
    tools: [],
  },
  [AgentType.JUDGE]: {
    ...BASE_CONFIG,
    id: AgentType.JUDGE,
    name: 'Judge Agent',
    systemPrompt: JUDGE_SYSTEM_PROMPT,
    description:
      'Impartial evaluator. Provides objective semantic verification and trust calibration.',
    category: AgentCategory.SYSTEM,
    icon: 'Gavel',
    enabled: true,
    reasoningProfile: ReasoningProfile.THINKING,
    defaultCommunicationMode: 'json',
    tools: [...UNIVERSAL_SYSTEM_TOOLS],
  },
};
