import { Octokit } from '@octokit/rest';

/**
 * The EvolutionManager identifies successful patterns and optimizations.
 * Instead of background extraction, it opens transparent GitHub Issues
 * to propose improvements to the user.
 */

export interface EvolutionProposal {
  id: string;
  name: string;
  description: string;
  rationale: string;
  impactScore: number; // 0-100 gain in AI-readiness
  suggestedDiff?: string;
}

export class EvolutionManager {
  private octokit: Octokit;
  private owner: string;
  private repo: string;

  constructor(githubToken: string, owner: string, repo: string) {
    this.octokit = new Octokit({ auth: githubToken });
    this.owner = owner;
    this.repo = repo;
  }

  /**
   * Proposes a discovered optimization as a transparent GitHub Issue.
   */
  public async proposeEvolution(proposal: EvolutionProposal): Promise<number> {
    const body = `
## 🚀 Evolution Proposal: ${proposal.name}

**Type:** Architecture Optimization
**AI-Readiness Impact:** +${proposal.impactScore}%

### 📝 Rationale
${proposal.rationale}

### 🔍 Description
${proposal.description}

${proposal.suggestedDiff ? `### 🛠️ Suggested Implementation\n\`\`\`typescript\n${proposal.suggestedDiff}\n\`\`\`` : ''}

---
*Generated by the ServerlessClaw Evolution Manager. This proposal is transparent and requires human review for local or hub-wide adoption.*
    `;

    const { data: issue } = await this.octokit.issues.create({
      owner: this.owner,
      repo: this.repo,
      title: `[EVOLUTION] Proposal: ${proposal.name}`,
      body,
      labels: ['evolution', 'proposal'],
    });

    console.log(`[EvolutionManager] Optimization proposed locally: ${issue.html_url}`);
    return issue.number;
  }

  /**
   * Shares an evolution proposal with the central ServerlessClaw Hub for community review.
   */
  public async shareWithHub(proposal: EvolutionProposal): Promise<void> {
    const hubOwner = 'serverlessclaw';
    const hubRepo = 'serverlessclaw';

    await this.octokit.issues.create({
      owner: hubOwner,
      repo: hubRepo,
      title: `[CONTRIBUTION] ${proposal.name} (from ${this.repo})`,
      body: `
## 🌟 New Pattern Proposed for Hub

**Origin:** ${this.owner}/${this.repo}
**Pattern:** ${proposal.name}
**Impact:** +${proposal.impactScore} AI Readiness

### Rationale
${proposal.rationale}

### Logic Overview
${proposal.description}

---
*Generated by EvolutionManager. This issue facilitates transparent community growth.*
      `,
      labels: ['contribution', 'triage'],
    });
  }

  /**
   * Reports a bug or AI-readiness regression.
   */
  public async reportRegression(message: string, severity: 'CRITICAL' | 'MAJOR' | 'MINOR'): Promise<void> {
    await this.octokit.issues.create({
      owner: this.owner,
      repo: this.repo,
      title: `[BUG] AI-Readiness Regression: ${severity}`,
      body: `**Severity:** ${severity}\n\n**Finding:** ${message}\n\n*Please address this to maintain optimal agent performance.*`,
      labels: ['bug', 'ai-readiness'],
    });
  }
}
